/** Curated IANA zones for the world clock picker (search filters this list). */
export const WORLD_CLOCK_ZONES: { id: string; label: string }[] = [
  { id: 'UTC', label: 'UTC' },
  { id: 'America/New_York', label: 'New York' },
  { id: 'America/Chicago', label: 'Chicago' },
  { id: 'America/Denver', label: 'Denver' },
  { id: 'America/Los_Angeles', label: 'Los Angeles' },
  { id: 'America/Phoenix', label: 'Phoenix' },
  { id: 'America/Toronto', label: 'Toronto' },
  { id: 'America/Vancouver', label: 'Vancouver' },
  { id: 'America/Mexico_City', label: 'Mexico City' },
  { id: 'America/Sao_Paulo', label: 'São Paulo' },
  { id: 'America/Buenos_Aires', label: 'Buenos Aires' },
  { id: 'Europe/London', label: 'London' },
  { id: 'Europe/Paris', label: 'Paris' },
  { id: 'Europe/Berlin', label: 'Berlin' },
  { id: 'Europe/Madrid', label: 'Madrid' },
  { id: 'Europe/Rome', label: 'Rome' },
  { id: 'Europe/Amsterdam', label: 'Amsterdam' },
  { id: 'Europe/Brussels', label: 'Brussels' },
  { id: 'Europe/Zurich', label: 'Zurich' },
  { id: 'Europe/Stockholm', label: 'Stockholm' },
  { id: 'Europe/Warsaw', label: 'Warsaw' },
  { id: 'Europe/Athens', label: 'Athens' },
  { id: 'Europe/Istanbul', label: 'Istanbul' },
  { id: 'Europe/Moscow', label: 'Moscow' },
  { id: 'Africa/Cairo', label: 'Cairo' },
  { id: 'Africa/Johannesburg', label: 'Johannesburg' },
  { id: 'Asia/Dubai', label: 'Dubai' },
  { id: 'Asia/Jerusalem', label: 'Jerusalem' },
  { id: 'Asia/Kolkata', label: 'Mumbai / India' },
  { id: 'Asia/Bangkok', label: 'Bangkok' },
  { id: 'Asia/Singapore', label: 'Singapore' },
  { id: 'Asia/Hong_Kong', label: 'Hong Kong' },
  { id: 'Asia/Shanghai', label: 'Shanghai' },
  { id: 'Asia/Tokyo', label: 'Tokyo' },
  { id: 'Asia/Seoul', label: 'Seoul' },
  { id: 'Australia/Sydney', label: 'Sydney' },
  { id: 'Australia/Melbourne', label: 'Melbourne' },
  { id: 'Australia/Perth', label: 'Perth' },
  { id: 'Pacific/Auckland', label: 'Auckland' },
  { id: 'Pacific/Honolulu', label: 'Honolulu' },
];
